// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// PDE_Kernel
NumericVector PDE_Kernel(NumericVector DataVector, NumericVector DomainX, double PR, int NSeq, int NData);
RcppExport SEXP _PDEBayes_PDE_Kernel(SEXP DataVectorSEXP, SEXP DomainXSEXP, SEXP PRSEXP, SEXP NSeqSEXP, SEXP NDataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DataVector(DataVectorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DomainX(DomainXSEXP);
    Rcpp::traits::input_parameter< double >::type PR(PRSEXP);
    Rcpp::traits::input_parameter< int >::type NSeq(NSeqSEXP);
    Rcpp::traits::input_parameter< int >::type NData(NDataSEXP);
    rcpp_result_gen = Rcpp::wrap(PDE_Kernel(DataVector, DomainX, PR, NSeq, NData));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PDEBayes_PDE_Kernel", (DL_FUNC) &_PDEBayes_PDE_Kernel, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PDEBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
