# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PDE_Kernel <- function(DataVector, DomainX, PR, NSeq, NData) {
    .Call(`_PDEBayes_PDE_Kernel`, DataVector, DomainX, PR, NSeq, NData)
}

